gen_name_eng = {
"bulbasaur" : [(1, "Bulbasaur")],
"ivysaur" : [(2, "Ivysaur")],
"venusaur" : [(3, "Venusaur")],
"charmander" : [(4, "Charmander")],
"charmeleon" : [(5, "Charmeleon")],
"charizard" : [(6, "Charizard")],
"squirtle" : [(7, "Squirtle")],
"wartortle" : [(8, "Wartortle")],
"blastoise" : [(9, "Blastoise")],
"caterpie" : [(10, "Caterpie")],
"metapod" : [(11, "Metapod")],
"butterfree" : [(12, "Butterfree")],
"weedle" : [(13, "Weedle")],
"kakuna" : [(14, "Kakuna")],
"beedrill" : [(15, "Beedrill")],
"pidgey" : [(16, "Pidgey")],
"pidgeotto" : [(17, "Pidgeotto")],
"pidgeot" : [(18, "Pidgeot")],
"rattata" : [(19, "Rattata")],
"raticate" : [(20, "Raticate")],
"spearow" : [(21, "Spearow")],
"fearow" : [(22, "Fearow")],
"ekans" : [(23, "Ekans")],
"arbok" : [(24, "Arbok")],
"pikachu" : [(25, "Pikachu")],
"raichu" : [(26, "Raichu")],
"sandshrew" : [(27, "Sandshrew")],
"sandslash" : [(28, "Sandslash")],
"nidoran" : [(29, "Nidoran ♀"), (32, "Nidoran ♂")],
"nidorina" : [(30, "Nidorina")],
"nidoqueen" : [(31, "Nidoqueen")],
"nidorino" : [(33, "Nidorino")],
"nidoking" : [(34, "Nidoking")],
"clefairy" : [(35, "Clefairy")],
"clefable" : [(36, "Clefable")],
"vulpix" : [(37, "Vulpix")],
"ninetales" : [(38, "Ninetales")],
"jigglypuff" : [(39, "Jigglypuff")],
"wigglytuff" : [(40, "Wigglytuff")],
"zubat" : [(41, "Zubat")],
"golbat" : [(42, "Golbat")],
"oddish" : [(43, "Oddish")],
"gloom" : [(44, "Gloom")],
"vileplume" : [(45, "Vileplume")],
"paras" : [(46, "Paras")],
"parasect" : [(47, "Parasect")],
"venonat" : [(48, "Venonat")],
"venomoth" : [(49, "Venomoth")],
"diglett" : [(50, "Diglett")],
"dugtrio" : [(51, "Dugtrio")],
"meowth" : [(52, "Meowth")],
"persian" : [(53, "Persian")],
"psyduck" : [(54, "Psyduck")],
"golduck" : [(55, "Golduck")],
"mankey" : [(56, "Mankey")],
"primeape" : [(57, "Primeape")],
"growlithe" : [(58, "Growlithe")],
"arcanine" : [(59, "Arcanine")],
"poliwag" : [(60, "Poliwag")],
"poliwhirl" : [(61, "Poliwhirl")],
"poliwrath" : [(62, "Poliwrath")],
"abra" : [(63, "Abra")],
"kadabra" : [(64, "Kadabra")],
"alakazam" : [(65, "Alakazam")],
"machop" : [(66, "Machop")],
"machoke" : [(67, "Machoke")],
"machamp" : [(68, "Machamp")],
"bellsprout" : [(69, "Bellsprout")],
"weepinbell" : [(70, "Weepinbell")],
"victreebel" : [(71, "Victreebel")],
"tentacool" : [(72, "Tentacool")],
"tentacruel" : [(73, "Tentacruel")],
"geodude" : [(74, "Geodude")],
"graveler" : [(75, "Graveler")],
"golem" : [(76, "Golem")],
"ponyta" : [(77, "Ponyta")],
"rapidash" : [(78, "Rapidash")],
"slowpoke" : [(79, "Slowpoke")],
"slowbro" : [(80, "Slowbro")],
"magnemite" : [(81, "Magnemite")],
"magneton" : [(82, "Magneton")],
"farfetchd" : [(83, "Farfetch'd")],
"doduo" : [(84, "Doduo")],
"dodrio" : [(85, "Dodrio")],
"seel" : [(86, "Seel")],
"dewgong" : [(87, "Dewgong")],
"grimer" : [(88, "Grimer")],
"muk" : [(89, "Muk")],
"shellder" : [(90, "Shellder")],
"cloyster" : [(91, "Cloyster")],
"gastly" : [(92, "Gastly")],
"haunter" : [(93, "Haunter")],
"gengar" : [(94, "Gengar")],
"onix" : [(95, "Onix")],
"drowzee" : [(96, "Drowzee")],
"hypno" : [(97, "Hypno")],
"krabby" : [(98, "Krabby")],
"kingler" : [(99, "Kingler")],
"voltorb" : [(100, "Voltorb")],
"electrode" : [(101, "Electrode")],
"exeggcute" : [(102, "Exeggcute")],
"exeggutor" : [(103, "Exeggutor")],
"cubone" : [(104, "Cubone")],
"marowak" : [(105, "Marowak")],
"hitmonlee" : [(106, "Hitmonlee")],
"hitmonchan" : [(107, "Hitmonchan")],
"lickitung" : [(108, "Lickitung")],
"koffing" : [(109, "Koffing")],
"weezing" : [(110, "Weezing")],
"rhyhorn" : [(111, "Rhyhorn")],
"rhydon" : [(112, "Rhydon")],
"chansey" : [(113, "Chansey")],
"tangela" : [(114, "Tangela")],
"kangaskhan" : [(115, "Kangaskhan")],
"horsea" : [(116, "Horsea")],
"seadra" : [(117, "Seadra")],
"goldeen" : [(118, "Goldeen")],
"seaking" : [(119, "Seaking")],
"staryu" : [(120, "Staryu")],
"starmie" : [(121, "Starmie")],
"mr mime" : [(122, "Mr. Mime")],
"mrmime" : [(122, "Mr. Mime")],
"mr. mime" : [(122, "Mr. Mime")],
"scyther" : [(123, "Scyther")],
"jynx" : [(124, "Jynx")],
"electabuzz" : [(125, "Electabuzz")],
"magmar" : [(126, "Magmar")],
"pinsir" : [(127, "Pinsir")],
"tauros" : [(128, "Tauros")],
"magikarp" : [(129, "Magikarp")],
"gyarados" : [(130, "Gyarados")],
"lapras" : [(131, "Lapras")],
"ditto" : [(132, "Ditto")],
"eevee" : [(133, "Eevee")],
"vaporeon" : [(134, "Vaporeon")],
"jolteon" : [(135, "Jolteon")],
"flareon" : [(136, "Flareon")],
"porygon" : [(137, "Porygon")],
"omanyte" : [(138, "Omanyte")],
"omastar" : [(139, "Omastar")],
"kabuto" : [(140, "Kabuto")],
"kabutops" : [(141, "Kabutops")],
"aerodactyl" : [(142, "Aerodactyl")],
"snorlax" : [(143, "Snorlax")],
"articuno" : [(144, "Articuno")],
"zapdos" : [(145, "Zapdos")],
"moltres" : [(146, "Moltres")],
"dratini" : [(147, "Dratini")],
"dragonair" : [(148, "Dragonair")],
"dragonite" : [(149, "Dragonite")],
"mewtwo" : [(150, "Mewtwo")],
"mew" : [(151, "Mew")]
}

gen_name_ger = {
"bisasam" : [(1, "Bisasam")],
"bisaknosp" : [(2, "Bisaknosp")],
"bisaflor" : [(3, "Bisaflor")],
"glumanda" : [(4, "Glumanda")],
"glutexo" : [(5, "Glutexo")],
"glurak" : [(6, "Glurak")],
"schiggy" : [(7, "Schiggy")],
"schillok" : [(8, "Schillok")],
"turtok" : [(9, "Turtok")],
"raupy" : [(10, "Raupy")],
"safcon" : [(11, "Safcon")],
"smettbo" : [(12, "Smettbo")],
"hornliu" : [(13, "Hornliu")],
"kokuna" : [(14, "Kokuna")],
"bibor" : [(15, "Bibor")],
"taubsi" : [(16, "Taubsi")],
"tauboga" : [(17, "Tauboga")],
"tauboss" : [(18, "Tauboss")],
"rattfratz" : [(19, "Rattfratz")],
"rattikarl" : [(20, "Rattikarl")],
"habitak" : [(21, "Habitak")],
"ibitak" : [(22, "Ibitak")],
"rettan" : [(23, "Rettan")],
"arbok" : [(24, "Arbok")],
"pikachu" : [(25, "Pikachu")],
"raichu" : [(26, "Raichu")],
"sandan" : [(27, "Sandan")],
"sandamer" : [(28, "Sandamer")],
"nidoran" : [(29, "Nidoran ♀"), (32, "Nidoran ♂")],
"nidorina" : [(30, "Nidorina")],
"nidoqueen" : [(31, "Nidoqueen")],
"nidorino" : [(33, "Nidorino")],
"nidoking" : [(34, "Nidoking")],
"piepi" : [(35, "Piepi")],
"pixi" : [(36, "Pixi")],
"vulpix" : [(37, "Vulpix")],
"vulnona" : [(38, "Vulnona")],
"pummeluff" : [(39, "Pummeluff")],
"knuddeluff" : [(40, "Knuddeluff")],
"zubat" : [(41, "Zubat")],
"golbat" : [(42, "Golbat")],
"myrapla" : [(43, "Myrapla")],
"duflor" : [(44, "Duflor")],
"giflor" : [(45, "Giflor")],
"paras" : [(46, "Paras")],
"parasect" : [(47, "Parasect")],
"bluzuk" : [(48, "Bluzuk")],
"omot" : [(49, "Omot")],
"digda" : [(50, "Digda")],
"digdri" : [(51, "Digdri")],
"mauzi" : [(52, "Mauzi")],
"snobilikat" : [(53, "Snobilikat")],
"enton" : [(54, "Enton")],
"entoron" : [(55, "Entoron")],
"menki" : [(56, "Menki")],
"rasaff" : [(57, "Rasaff")],
"fukano" : [(58, "Fukano")],
"arkani" : [(59, "Arkani")],
"quapsel" : [(60, "Quapsel")],
"quaputzi" : [(61, "Quaputzi")],
"quappo" : [(62, "Quappo")],
"abra" : [(63, "Abra")],
"kadabra" : [(64, "Kadabra")],
"simsala" : [(65, "Simsala")],
"machollo" : [(66, "Machollo")],
"maschok" : [(67, "Maschok")],
"machomei" : [(68, "Machomei")],
"knofensa" : [(69, "Knofensa")],
"ultrigaria" : [(70, "Ultrigaria")],
"sarzenia" : [(71, "Sarzenia")],
"tentacha" : [(72, "Tentacha")],
"tentoxa" : [(73, "Tentoxa")],
"kleinstein" : [(74, "Kleinstein")],
"georok" : [(75, "Georok")],
"geowaz" : [(76, "Geowaz")],
"ponita" : [(77, "Ponita")],
"gallopa" : [(78, "Gallopa")],
"flegmon" : [(79, "Flegmon")],
"lahmus" : [(80, "Lahmus")],
"magnetilo" : [(81, "Magnetilo")],
"magneton" : [(82, "Magneton")],
"porenta" : [(83, "Porenta")],
"dodu" : [(84, "Dodu")],
"dodri" : [(85, "Dodri")],
"jurob" : [(86, "Jurob")],
"jugong" : [(87, "Jugong")],
"sleima" : [(88, "Sleima")],
"sleimok" : [(89, "Sleimok")],
"muschas" : [(90, "Muschas")],
"austos" : [(91, "Austos")],
"nebulak" : [(92, "Nebulak")],
"alpollo" : [(93, "Alpollo")],
"gengar" : [(94, "Gengar")],
"onix" : [(95, "Onix")],
"traumato" : [(96, "Traumato")],
"hypno" : [(97, "Hypno")],
"krabby" : [(98, "Krabby")],
"kingler" : [(99, "Kingler")],
"voltoball" : [(100, "Voltoball")],
"lectroball" : [(101, "Lectroball")],
"owei" : [(102, "Owei")],
"kokowei" : [(103, "Kokowei")],
"tragosso" : [(104, "Tragosso")],
"knogga" : [(105, "Knogga")],
"kicklee" : [(106, "Kicklee")],
"nockchan" : [(107, "Nockchan")],
"schlurp" : [(108, "Schlurp")],
"smogon" : [(109, "Smogon")],
"smogmog" : [(110, "Smogmog")],
"rihorn" : [(111, "Rihorn")],
"rizeros" : [(112, "Rizeros")],
"chaneira" : [(113, "Chaneira")],
"tangela" : [(114, "Tangela")],
"kangama" : [(115, "Kangama")],
"seeper" : [(116, "Seeper")],
"seemon" : [(117, "Seemon")],
"goldini" : [(118, "Goldini")],
"golking" : [(119, "Golking")],
"sterndu" : [(120, "Sterndu")],
"starmie" : [(121, "Starmie")],
"pantimos" : [(122, "Pantimos")],
"sichlor" : [(123, "Sichlor")],
"rossana" : [(124, "Rossana")],
"elektek" : [(125, "Elektek")],
"magmar" : [(126, "Magmar")],
"pinsir" : [(127, "Pinsir")],
"tauros" : [(128, "Tauros")],
"karpador" : [(129, "Karpador")],
"garados" : [(130, "Garados")],
"lapras" : [(131, "Lapras")],
"ditto" : [(132, "Ditto")],
"evoli" : [(133, "Evoli")],
"aquana" : [(134, "Aquana")],
"blitza" : [(135, "Blitza")],
"flamara" : [(136, "Flamara")],
"porygon" : [(137, "Porygon")],
"amonitas" : [(138, "Amonitas")],
"amoroso" : [(139, "Amoroso")],
"kabuto" : [(140, "Kabuto")],
"kabutops" : [(141, "Kabutops")],
"aerodactyl" : [(142, "Aerodactyl")],
"relaxo" : [(143, "Relaxo")],
"arktos" : [(144, "Arktos")],
"zapdos" : [(145, "Zapdos")],
"lavados" : [(146, "Lavados")],
"dratini" : [(147, "Dratini")],
"dragonir" : [(148, "Dragonir")],
"dragoran" : [(149, "Dragoran")],
"mewtu" : [(150, "Mewtu")],
"mew" : [(151, "Mew")]
}

gen_name_all = {**gen_name_eng, **gen_name_ger}

gen_id_all = {
1 : "Bulbasaur",
2 : "Ivysaur",
3 : "Venusaur",
4 : "Charmander",
5 : "Charmeleon",
6 : "Charizard",
7 : "Squirtle",
8 : "Wartortle",
9 : "Blastoise",
10 : "Caterpie",
11 : "Metapod",
12 : "Butterfree",
13 : "Weedle",
14 : "Kakuna",
15 : "Beedrill",
16 : "Pidgey",
17 : "Pidgeotto",
18 : "Pidgeot",
19 : "Rattata",
20 : "Raticate",
21 : "Spearow",
22 : "Fearow",
23 : "Ekans",
24 : "Arbok",
25 : "Pikachu",
26 : "Raichu",
27 : "Sandshrew",
28 : "Sandslash",
29 : "Nidoran ♀",
30 : "Nidorina",
31 : "Nidoqueen",
32 : "Nidoran ♂",
33 : "Nidorino",
34 : "Nidoking",
35 : "Clefairy",
36 : "Clefable",
37 : "Vulpix",
38 : "Ninetales",
39 : "Jigglypuff",
40 : "Wigglytuff",
41 : "Zubat",
42 : "Golbat",
43 : "Oddish",
44 : "Gloom",
45 : "Vileplume",
46 : "Paras",
47 : "Parasect",
48 : "Venonat",
49 : "Venomoth",
50 : "Diglett",
51 : "Dugtrio",
52 : "Meowth",
53 : "Persian",
54 : "Psyduck",
55 : "Golduck",
56 : "Mankey",
57 : "Primeape",
58 : "Growlithe",
59 : "Arcanine",
60 : "Poliwag",
61 : "Poliwhirl",
62 : "Poliwrath",
63 : "Abra",
64 : "Kadabra",
65 : "Alakazam",
66 : "Machop",
67 : "Machoke",
68 : "Machamp",
69 : "Bellsprout",
70 : "Weepinbell",
71 : "Victreebel",
72 : "Tentacool",
73 : "Tentacruel",
74 : "Geodude",
75 : "Graveler",
76 : "Golem",
77 : "Ponyta",
78 : "Rapidash",
79 : "Slowpoke",
80 : "Slowbro",
81 : "Magnemite",
82 : "Magneton",
83 : "Farfetch'd",
84 : "Doduo",
85 : "Dodrio",
86 : "Seel",
87 : "Dewgong",
88 : "Grimer",
89 : "Muk",
90 : "Shellder",
91 : "Cloyster",
92 : "Gastly",
93 : "Haunter",
94 : "Gengar",
95 : "Onix",
96 : "Drowzee",
97 : "Hypno",
98 : "Krabby",
99 : "Kingler",
100 : "Voltorb",
101 : "Electrode",
102 : "Exeggcute",
103 : "Exeggutor",
104 : "Cubone",
105 : "Marowak",
106 : "Hitmonlee",
107 : "Hitmonchan",
108 : "Lickitung",
109 : "Koffing",
110 : "Weezing",
111 : "Rhyhorn",
112 : "Rhydon",
113 : "Chansey",
114 : "Tangela",
115 : "Kangaskhan",
116 : "Horsea",
117 : "Seadra",
118 : "Goldeen",
119 : "Seaking",
120 : "Staryu",
121 : "Starmie",
122 : "Mr. Mime",
123 : "Scyther",
124 : "Jynx",
125 : "Electabuzz",
126 : "Magmar",
127 : "Pinsir",
128 : "Tauros",
129 : "Magikarp",
130 : "Gyarados",
131 : "Lapras",
132 : "Ditto",
133 : "Eevee",
134 : "Vaporeon",
135 : "Jolteon",
136 : "Flareon",
137 : "Porygon",
138 : "Omanyte",
139 : "Omastar",
140 : "Kabuto",
141 : "Kabutops",
142 : "Aerodactyl",
143 : "Snorlax",
144 : "Articuno",
145 : "Zapdos",
146 : "Moltres",
147 : "Dratini",
148 : "Dragonair",
149 : "Dragonite",
150 : "Mewtwo",
151 : "Mew"
}

gen_id_eng = gen_id_all

gen_id_ger = {
1 : "Bisasam",
2 : "Bisaknosp",
3 : "Bisaflor",
4 : "Glumanda",
5 : "Glutexo",
6 : "Glurak",
7 : "Schiggy",
8 : "Schillok",
9 : "Turtok",
10 : "Raupy",
11 : "Safcon",
12 : "Smettbo",
13 : "Hornliu",
14 : "Kokuna",
15 : "Bibor",
16 : "Taubsi",
17 : "Tauboga",
18 : "Tauboss",
19 : "Rattfratz",
20 : "Rattikarl",
21 : "Habitak",
22 : "Ibitak",
23 : "Rettan",
24 : "Arbok",
25 : "Pikachu",
26 : "Raichu",
27 : "Sandan",
28 : "Sandamer",
29 : "Nidoran ♀",
30 : "Nidorina",
31 : "Nidoqueen",
32 : "Nidoran ♂",
33 : "Nidorino",
34 : "Nidoking",
35 : "Piepi",
36 : "Pixi",
37 : "Vulpix",
38 : "Vulnona",
39 : "Pummeluff",
40 : "Knuddeluff",
41 : "Zubat",
42 : "Golbat",
43 : "Myrapla",
44 : "Duflor",
45 : "Giflor",
46 : "Paras",
47 : "Parasect",
48 : "Bluzuk",
49 : "Omot",
50 : "Digda",
51 : "Digdri",
52 : "Mauzi",
53 : "Snobilikat",
54 : "Enton",
55 : "Entoron",
56 : "Menki",
57 : "Rasaff",
58 : "Fukano",
59 : "Arkani",
60 : "Quapsel",
61 : "Quaputzi",
62 : "Quappo",
63 : "Abra",
64 : "Kadabra",
65 : "Simsala",
66 : "Machollo",
67 : "Maschok",
68 : "Machomei",
69 : "Knofensa",
70 : "Ultrigaria",
71 : "Sarzenia",
72 : "Tentacha",
73 : "Tentoxa",
74 : "Kleinstein",
75 : "Georok",
76 : "Geowaz",
77 : "Ponita",
78 : "Gallopa",
79 : "Flegmon",
80 : "Lahmus",
81 : "Magnetilo",
82 : "Magneton",
83 : "Porenta",
84 : "Dodu",
85 : "Dodri",
86 : "Jurob",
87 : "Jugong",
88 : "Sleima",
89 : "Sleimok",
90 : "Muschas",
91 : "Austos",
92 : "Nebulak",
93 : "Alpollo",
94 : "Gengar",
95 : "Onix",
96 : "Traumato",
97 : "Hypno",
98 : "Krabby",
99 : "Kingler",
100 : "Voltoball",
101 : "Lectroball",
102 : "Owei",
103 : "Kokowei",
104 : "Tragosso",
105 : "Knogga",
106 : "Kicklee",
107 : "Nockchan",
108 : "Schlurp",
109 : "Smogon",
110 : "Smogmog",
111 : "Rihorn",
112 : "Rizeros",
113 : "Chaneira",
114 : "Tangela",
115 : "Kangama",
116 : "Seeper",
117 : "Seemon",
118 : "Goldini",
119 : "Golking",
120 : "Sterndu",
121 : "Starmie",
122 : "Pantimos",
123 : "Sichlor",
124 : "Rossana",
125 : "Elektek",
126 : "Magmar",
127 : "Pinsir",
128 : "Tauros",
129 : "Karpador",
130 : "Garados",
131 : "Lapras",
132 : "Ditto",
133 : "Evoli",
134 : "Aquana",
135 : "Blitza",
136 : "Flamara",
137 : "Porygon",
138 : "Amonitas",
139 : "Amoroso",
140 : "Kabuto",
141 : "Kabutops",
142 : "Aerodactyl",
143 : "Relaxo",
144 : "Arktos",
145 : "Zapdos",
146 : "Lavados",
147 : "Dratini",
148 : "Dragonir",
149 : "Dragoran",
150 : "Mewtu",
151 : "Mew"
}