
gen_name_eng = {
    "rowlet" : [(722, "Rowlet")],
    "dartrix" : [(723, "Dartrix")],
    "decidueye" : [(724, "Decidueye")],
    "litten" : [(725, "Litten")],
    "torracat" : [(726, "Torracat")],
    "incineroar" : [(727, "Incineroar")],
    "popplio" : [(728, "Popplio")],
    "brionne" : [(729, "Brionne")],
    "primarina" : [(730, "Primarina")],
    "pikipek" : [(731, "Pikipek")],
    "trumbeak" : [(732, "Trumbeak")],
    "toucannon" : [(733, "Toucannon")],
    "yungoos" : [(734, "Yungoos")],
    "gumshoos" : [(735, "Gumshoos")],
    "grubbin" : [(736, "Grubbin")],
    "charjabug" : [(737, "Charjabug")],
    "vikavolt" : [(738, "Vikavolt")],
    "crabrawler" : [(739, "Crabrawler")],
    "crabominable" : [(740, "Crabominable")],
    "oricorio" : [(741, "Oricorio")],
    "cutiefly" : [(742, "Cutiefly")],
    "ribombee" : [(743, "Ribombee")],
    "rockruff" : [(744, "Rockruff")],
    "lycanroc" : [(745, "Lycanroc")],
    "wishiwashi" : [(746, "Wishiwashi")],
    "mareanie" : [(747, "Mareanie")],
    "toxapex" : [(748, "Toxapex")],
    "mudbray" : [(749, "Mudbray")],
    "mudsdale" : [(750, "Mudsdale")],
    "dewpider" : [(751, "Dewpider")],
    "araquanid" : [(752, "Araquanid")],
    "fomantis" : [(753, "Fomantis")],
    "lurantis" : [(754, "Lurantis")],
    "morelull" : [(755, "Morelull")],
    "shiinotic" : [(756, "Shiinotic")],
    "salandit" : [(757, "Salandit")],
    "salazzle" : [(758, "Salazzle")],
    "stufful" : [(759, "Stufful")],
    "bewear" : [(760, "Bewear")],
    "bounsweet" : [(761, "Bounsweet")],
    "steenee" : [(762, "Steenee")],
    "tsareena" : [(763, "Tsareena")],
    "comfey" : [(764, "Comfey")],
    "oranguru" : [(765, "Oranguru")],
    "passimian" : [(766, "Passimian")],
    "wimpod" : [(767, "Wimpod")],
    "golisopod" : [(768, "Golisopod")],
    "sandygast" : [(769, "Sandygast")],
    "palossand" : [(770, "Palossand")],
    "pyukumuku" : [(771, "Pyukumuku")],
    "type: null" : [(772, "Type: Null")],
    "type:null" : [(772, "Type: Null")],
    "type null" : [(772, "Type: Null")],
    "typenull" : [(772, "Type: Null")],
    "silvally" : [(773, "Silvally")],
    "minior" : [(774, "Minior")],
    "komala" : [(775, "Komala")],
    "turtonator" : [(776, "Turtonator")],
    "togedemaru" : [(777, "Togedemaru")],
    "mimikyu" : [(778, "Mimikyu")],
    "bruxish" : [(779, "Bruxish")],
    "drampa" : [(780, "Drampa")],
    "dhelmise" : [(781, "Dhelmise")],
    "jangmo" : [(782, "Jangmo")],
    "hakamo" : [(783, "Hakamo")],
    "kommo" : [(784, "Kommo")],
    "tapu koko" : [(785, "Tapu Koko")],
    "tapu-koko" : [(785, "Tapu Koko")],
    "tapukoko" : [(785, "Tapu Koko")],
    "tapu lele" : [(786, "Tapu Lele")],
    "tapu-lele" : [(786, "Tapu Lele")],
    "tapulele" : [(786, "Tapu Lele")],
    "tapu bulu" : [(787, "Tapu Bulu")],
    "tapu-bulu" : [(787, "Tapu Bulu")],
    "tapubulu" : [(787, "Tapu Bulu")],
    "tapu fini" : [(788, "Tapu Fini")],
    "tapu-fini" : [(788, "Tapu Fini")],
    "tapufini" : [(788, "Tapu Fini")],
    "cosmog" : [(789, "Cosmog")],
    "cosmoem" : [(790, "Cosmoem")],
    "solgaleo" : [(791, "Solgaleo")],
    "lunala" : [(792, "Lunala")],
    "nihilego" : [(793, "Nihilego")],
    "buzzwole" : [(794, "Buzzwole")],
    "pheromosa" : [(795, "Pheromosa")],
    "xurkitree" : [(796, "Xurkitree")],
    "celesteela" : [(797, "Celesteela")],
    "kartana" : [(798, "Kartana")],
    "guzzlord" : [(799, "Guzzlord")],
    "necrozma" : [(800, "Necrozma")],
    "magearna" : [(801, "Magearna")],
    "marshadow" : [(802, "Marshadow")],
    "poipole" : [(803, "Poipole")],
    "naganadel" : [(804, "Naganadel")],
    "stakataka" : [(805, "Stakataka")],
    "blacephalon" : [(806, "Blacephalon")],
    "zeraora" : [(807, "Zeraora")],
    "meltan" : [(808, "Meltan")],
    "melmetal" : [(809, "Melmetal")],
}

gen_name_ger = {
    "bauz" : [(722, "Bauz")],
    "arboretoss" : [(723, "Arboretoss")],
    "silvarro" : [(724, "Silvarro")],
    "flamiau" : [(725, "Flamiau")],
    "miezunder" : [(726, "Miezunder")],
    "fuegro" : [(727, "Fuegro")],
    "robball" : [(728, "Robball")],
    "marikeck" : [(729, "Marikeck")],
    "primarene" : [(730, "Primarene")],
    "peppeck" : [(731, "Peppeck")],
    "trompeck" : [(732, "Trompeck")],
    "tukanon" : [(733, "Tukanon")],
    "mangunior" : [(734, "Mangunior")],
    "manguspektor" : [(735, "Manguspektor")],
    "mabula" : [(736, "Mabula")],
    "akkup" : [(737, "Akkup")],
    "donarion" : [(738, "Donarion")],
    "krabbox" : [(739, "Krabbox")],
    "krawell" : [(740, "Krawell")],
    "choreogel" : [(741, "Choreogel")],
    "wommel" : [(742, "Wommel")],
    "bandelby" : [(743, "Bandelby")],
    "wuffels" : [(744, "Wuffels")],
    "wolwerock" : [(745, "Wolwerock")],
    "lusardin" : [(746, "Lusardin")],
    "garstella" : [(747, "Garstella")],
    "aggrostella" : [(748, "Aggrostella")],
    "pampuli" : [(749, "Pampuli")],
    "pampross" : [(750, "Pampross")],
    "araqua" : [(751, "Araqua")],
    "aranestro" : [(752, "Aranestro")],
    "imantis" : [(753, "Imantis")],
    "mantidea" : [(754, "Mantidea")],
    "bubungus" : [(755, "Bubungus")],
    "lamellux" : [(756, "Lamellux")],
    "molunk" : [(757, "Molunk")],
    "amfira" : [(758, "Amfira")],
    "velursi" : [(759, "Velursi")],
    "kosturso" : [(760, "Kosturso")],
    "frubberl" : [(761, "Frubberl")],
    "frubaila" : [(762, "Frubaila")],
    "fruyal" : [(763, "Fruyal")],
    "curelei" : [(764, "Curelei")],
    "kommandutan" : [(765, "Kommandutan")],
    "quartermak" : [(766, "Quartermak")],
    "reißlaus" : [(767, "Reißlaus")],
    "reisslaus" : [(767, "Reißlaus")],
    "tectass" : [(768, "Tectass")],
    "sankabuh" : [(769, "Sankabuh")],
    "colossand" : [(770, "Colossand")],
    "gufa" : [(771, "Gufa")],
    "typ:null" : [(772, "Typ:Null")],
    "typ-null" : [(772, "Typ:Null")],
    "typ null" : [(772, "Typ:Null")],
    "typnull" : [(772, "Typ:Null")],
    "amigento" : [(773, "Amigento")],
    "meteno" : [(774, "Meteno")],
    "koalelu" : [(775, "Koalelu")],
    "tortunator" : [(776, "Tortunator")],
    "togedemaru" : [(777, "Togedemaru")],
    "mimigma" : [(778, "Mimigma")],
    "knirfish" : [(779, "Knirfish")],
    "sen-long" : [(780, "Sen-Long")],
    "sen long" : [(780, "Sen-Long")],
    "senlong" : [(780, "Sen-Long")],
    "moruda" : [(781, "Moruda")],
    "miniras" : [(782, "Miniras")],
    "mediras" : [(783, "Mediras")],
    "grandiras" : [(784, "Grandiras")],
    "kapu-riki" : [(785, "Kapu-Riki")],
    "kapu riki" : [(785, "Kapu-Riki")],
    "kapuriki" : [(785, "Kapu-Riki")],
    "kapu-fala" : [(786, "Kapu-Fala")],
    "kapu fala" : [(786, "Kapu-Fala")],
    "kapufala" : [(786, "Kapu-Fala")],
    "kapu-toro" : [(787, "Kapu-Toro")],
    "kapu toro" : [(787, "Kapu-Toro")],
    "kaputoro" : [(787, "Kapu-Toro")],
    "kapu-kime" : [(788, "Kapu-Kime")],
    "kapu kime" : [(788, "Kapu-Kime")],
    "kapukime" : [(788, "Kapu-Kime")],
    "cosmog" : [(789, "Cosmog")],
    "cosmovum" : [(790, "Cosmovum")],
    "solgaleo" : [(791, "Solgaleo")],
    "lunala" : [(792, "Lunala")],
    "anego" : [(793, "Anego")],
    "masskito" : [(794, "Masskito")],
    "schabelle" : [(795, "Schabelle")],
    "voltriant" : [(796, "Voltriant")],
    "kaguron" : [(797, "Kaguron")],
    "katagami" : [(798, "Katagami")],
    "schlingking" : [(799, "Schlingking")],
    "necrozma" : [(800, "Necrozma")],
    "magearna" : [(801, "Magearna")],
    "marshadow" : [(802, "Marshadow")],
    "venicro" : [(803, "Venicro")],
    "agoyon" : [(804, "Agoyon")],
    "muramura" : [(805, "Muramura")],
    "kopplosio" : [(806, "Kopplosio")],
    "zeraora" : [(807, "Zeraora")],
    "meltan" : [(808, "Meltan")],
    "melmetal" : [(809, "Melmetal")],
}

gen_name_all = {**gen_name_eng, **gen_name_ger}

gen_id_eng = {
    722 : "Rowlet",
    723 : "Dartrix",
    724 : "Decidueye",
    725 : "Litten",
    726 : "Torracat",
    727 : "Incineroar",
    728 : "Popplio",
    729 : "Brionne",
    730 : "Primarina",
    731 : "Pikipek",
    732 : "Trumbeak",
    733 : "Toucannon",
    734 : "Yungoos",
    735 : "Gumshoos",
    736 : "Grubbin",
    737 : "Charjabug",
    738 : "Vikavolt",
    739 : "Crabrawler",
    740 : "Crabominable",
    741 : "Oricorio",
    742 : "Cutiefly",
    743 : "Ribombee",
    744 : "Rockruff",
    745 : "Lycanroc",
    746 : "Wishiwashi",
    747 : "Mareanie",
    748 : "Toxapex",
    749 : "Mudbray",
    750 : "Mudsdale",
    751 : "Dewpider",
    752 : "Araquanid",
    753 : "Fomantis",
    754 : "Lurantis",
    755 : "Morelull",
    756 : "Shiinotic",
    757 : "Salandit",
    758 : "Salazzle",
    759 : "Stufful",
    760 : "Bewear",
    761 : "Bounsweet",
    762 : "Steenee",
    763 : "Tsareena",
    764 : "Comfey",
    765 : "Oranguru",
    766 : "Passimian",
    767 : "Wimpod",
    768 : "Golisopod",
    769 : "Sandygast",
    770 : "Palossand",
    771 : "Pyukumuku",
    772 : "Type: Null",
    773 : "Silvally",
    774 : "Minior",
    775 : "Komala",
    776 : "Turtonator",
    777 : "Togedemaru",
    778 : "Mimikyu",
    779 : "Bruxish",
    780 : "Drampa",
    781 : "Dhelmise",
    782 : "Jangmo",
    783 : "Hakamo",
    784 : "Kommo",
    785 : "Tapu Koko",
    786 : "Tapu Lele",
    787 : "Tapu Bulu",
    788 : "Tapu Fini",
    789 : "Cosmog",
    790 : "Cosmoem",
    791 : "Solgaleo",
    792 : "Lunala",
    793 : "Nihilego",
    794 : "Buzzwole",
    795 : "Pheromosa",
    796 : "Xurkitree",
    797 : "Celesteela",
    798 : "Kartana",
    799 : "Guzzlord",
    800 : "Necrozma",
    801 : "Magearna",
    802 : "Marshadow",
    803 : "Poipole",
    804 : "Naganadel",
    805 : "Stakataka",
    806 : "Blacephalon",
    807 : "Zeraora",
    808 : "Meltan",
    809 : "Melmetal",
}

gen_id_all = gen_id_eng

gen_id_ger = {
    722 : "Bauz",
    723 : "Arboretoss",
    724 : "Silvarro",
    725 : "Flamiau",
    726 : "Miezunder",
    727 : "Fuegro",
    728 : "Robball",
    729 : "Marikeck",
    730 : "Primarene",
    731 : "Peppeck",
    732 : "Trompeck",
    733 : "Tukanon",
    734 : "Mangunior",
    735 : "Manguspektor",
    736 : "Mabula",
    737 : "Akkup",
    738 : "Donarion",
    739 : "Krabbox",
    740 : "Krawell",
    741 : "Choreogel",
    742 : "Wommel",
    743 : "Bandelby",
    744 : "Wuffels",
    745 : "Wolwerock",
    746 : "Lusardin",
    747 : "Garstella",
    748 : "Aggrostella",
    749 : "Pampuli",
    750 : "Pampross",
    751 : "Araqua",
    752 : "Aranestro",
    753 : "Imantis",
    754 : "Mantidea",
    755 : "Bubungus",
    756 : "Lamellux",
    757 : "Molunk",
    758 : "Amfira",
    759 : "Velursi",
    760 : "Kosturso",
    761 : "Frubberl",
    762 : "Frubaila",
    763 : "Fruyal",
    764 : "Curelei",
    765 : "Kommandutan",
    766 : "Quartermak",
    767 : "Reißlaus",
    768 : "Tectass",
    769 : "Sankabuh",
    770 : "Colossand",
    771 : "Gufa",
    772 : "Typ:Null",
    773 : "Amigento",
    774 : "Meteno",
    775 : "Koalelu",
    776 : "Tortunator",
    777 : "Togedemaru",
    778 : "Mimigma",
    779 : "Knirfish",
    780 : "Sen-Long",
    781 : "Moruda",
    782 : "Miniras",
    783 : "Mediras",
    784 : "Grandiras",
    785 : "Kapu-Riki",
    786 : "Kapu-Fala",
    787 : "Kapu-Toro",
    788 : "Kapu-Kime",
    789 : "Cosmog",
    790 : "Cosmovum",
    791 : "Solgaleo",
    792 : "Lunala",
    793 : "Anego",
    794 : "Masskito",
    795 : "Schabelle",
    796 : "Voltriant",
    797 : "Kaguron",
    798 : "Katagami",
    799 : "Schlingking",
    800 : "Necrozma",
    801 : "Magearna",
    802 : "Marshadow",
    803 : "Venicro",
    804 : "Agoyon",
    805 : "Muramura",
    806 : "Kopplosio",
    807 : "Zeraora",
    808 : "Meltan",
    809 : "Melmetal",
}