gen_name_eng = {
    "grookey" : [(810, "Grookey")],
    "thwackey" : [(811, "Thwackey")],
    "rillaboom" : [(812, "Rillaboom")],
    "scorbunny" : [(813, "Scorbunny")],
    "raboot" : [(814, "Raboot")],
    "cinderace" : [(815, "Cinderace")],
    "sobble" : [(816, "Sobble")],
    "drizzile" : [(817, "Drizzile")],
    "inteleon" : [(818, "Inteleon")],
    "skwovet" : [(819, "Skwovet")],
    "greedent" : [(820, "Greedent")],
    "rookidee" : [(821, "Rookidee")],
    "corvisquire" : [(822, "Corvisquire")],
    "corviknight" : [(823, "Corviknight")],
    "blipbug" : [(824, "Blipbug")],
    "dottler" : [(825, "Dottler")],
    "orbeetle" : [(826, "Orbeetle")],
    "nickit" : [(827, "Nickit")],
    "thievul" : [(828, "Thievul")],
    "gossifleur" : [(829, "Gossifleur")],
    "eldegoss" : [(830, "Eldegoss")],
    "wooloo" : [(831, "Wooloo")],
    "dubwool" : [(832, "Dubwool")],
    "chewtle" : [(833, "Chewtle")],
    "drednaw" : [(834, "Drednaw")],
    "yamper" : [(835, "Yamper")],
    "boltund" : [(836, "Boltund")],
    "rolycoly" : [(837, "Rolycoly")],
    "carkol" : [(838, "Carkol")],
    "coalossal" : [(839, "Coalossal")],
    "applin" : [(840, "Applin")],
    "flapple" : [(841, "Flapple")],
    "appletun" : [(842, "Appletun")],
    "silicobra" : [(843, "Silicobra")],
    "sandaconda" : [(844, "Sandaconda")],
    "cramorant" : [(845, "Cramorant")],
    "arrokuda" : [(846, "Arrokuda")],
    "barraskewda" : [(847, "Barraskewda")],
    "toxel" : [(848, "Toxel")],
    "toxtricity" : [(849, "Toxtricity")],
    "sizzlipede" : [(850, "Sizzlipede")],
    "centiskorch" : [(851, "Centiskorch")],
    "clobbopus" : [(852, "Clobbopus")],
    "grapploct" : [(853, "Grapploct")],
    "sinistea" : [(854, "Sinistea")],
    "polteageist" : [(855, "Polteageist")],
    "hatenna" : [(856, "Hatenna")],
    "hattrem" : [(857, "Hattrem")],
    "hatterene" : [(858, "Hatterene")],
    "impidimp" : [(859, "Impidimp")],
    "morgrem" : [(860, "Morgrem")],
    "grimmsnarl" : [(861, "Grimmsnarl")],
    "obstagoon" : [(862, "Obstagoon")],
    "perrserker" : [(863, "Perrserker")],
    "cursola" : [(864, "Cursola")],
    "sirfetch’d" : [(865, "Sirfetch’d")],
    "sirfetchd" : [(865, "Sirfetch’d")],
    "mr rime" : [(866, "Mr. Rime")],
    "mrrime" : [(866, "Mr. Rime")],
    "mr. rime" : [(866, "Mr. Rime")],
    "runerigus" : [(867, "Runerigus")],
    "milcery" : [(868, "Milcery")],
    "alcremie" : [(869, "Alcremie")],
    "falinks" : [(870, "Falinks")],
    "pincurchin" : [(871, "Pincurchin")],
    "snom" : [(872, "Snom")],
    "frosmoth" : [(873, "Frosmoth")],
    "stonjourner" : [(874, "Stonjourner")],
    "eiscue" : [(875, "Eiscue")],
    "indeedee" : [(876, "Indeedee")],
    "morpeko" : [(877, "Morpeko")],
    "cufant" : [(878, "Cufant")],
    "copperajah" : [(879, "Copperajah")],
    "dracozolt" : [(880, "Dracozolt")],
    "arctozolt" : [(881, "Arctozolt")],
    "dracovish" : [(882, "Dracovish")],
    "arctovish" : [(883, "Arctovish")],
    "duraludon" : [(884, "Duraludon")],
    "dreepy" : [(885, "Dreepy")],
    "drakloak" : [(886, "Drakloak")],
    "dragapult" : [(887, "Dragapult")],
    "zacian" : [(888, "Zacian")],
    "zamazenta" : [(889, "Zamazenta")],
    "eternatus" : [(890, "Eternatus")],
    "kubfu" : [(891, "Kubfu")],
    "urshifu" : [(892, "Urshifu")],
    "zarude" : [(893, "Zarude")],
    "regieleki" : [(894, "Regieleki")],
    "regidrago" : [(895, "Regidrago")],
    "glastrier" : [(896, "Glastrier")],
    "spectrier" : [(897, "Spectrier")],
    "calyrex" : [(898, "Calyrex")],
    "wyrdeer" : [(899, "Wyrdeer")],
    "kleavor" : [(900, "Kleavor")],
    "ursaluna" : [(901, "Ursaluna")],
    "basculegion" : [(902, "Basculegion")],
    "sneasler" : [(903, "Sneasler")],
    "overqwil" : [(904, "Overqwil")],
    "enamorus" : [(905, "Enamorus")],
}

gen_name_ger = {
    "chimpep" : [(810, "Chimpep")],
    "chimstix" : [(811, "Chimstix")],
    "gortrom" : [(812, "Gortrom")],
    "hopplo" : [(813, "Hopplo")],
    "kickerlo" : [(814, "Kickerlo")],
    "liberlo" : [(815, "Liberlo")],
    "memmeon" : [(816, "Memmeon")],
    "phlegleon" : [(817, "Phlegleon")],
    "intelleon" : [(818, "Intelleon")],
    "raffel" : [(819, "Raffel")],
    "schlaraffel" : [(820, "Schlaraffel")],
    "meikro" : [(821, "Meikro")],
    "kranoviz" : [(822, "Kranoviz")],
    "krarmor" : [(823, "Krarmor")],
    "sensect" : [(824, "Sensect")],
    "keradar" : [(825, "Keradar")],
    "maritellit" : [(826, "Maritellit")],
    "kleptifux" : [(827, "Kleptifux")],
    "gaunux" : [(828, "Gaunux")],
    "cottini" : [(829, "Cottini")],
    "cottomi" : [(830, "Cottomi")],
    "wolly" : [(831, "Wolly")],
    "zwollock" : [(832, "Zwollock")],
    "kamehaps" : [(833, "Kamehaps")],
    "kamalm" : [(834, "Kamalm")],
    "voldi" : [(835, "Voldi")],
    "bellektro" : [(836, "Bellektro")],
    "klonkett" : [(837, "Klonkett")],
    "wagong" : [(838, "Wagong")],
    "montecarbo" : [(839, "Montecarbo")],
    "knapfel" : [(840, "Knapfel")],
    "drapfel" : [(841, "Drapfel")],
    "schlapfel" : [(842, "Schlapfel")],
    "salanga" : [(843, "Salanga")],
    "sanaconda" : [(844, "Sanaconda")],
    "urgl" : [(845, "Urgl")],
    "pikuda" : [(846, "Pikuda")],
    "barrakiefa" : [(847, "Barrakiefa")],
    "toxel" : [(848, "Toxel")],
    "riffex" : [(849, "Riffex")],
    "thermopod" : [(850, "Thermopod")],
    "infernopod" : [(851, "Infernopod")],
    "klopptopus" : [(852, "Klopptopus")],
    "kaocto" : [(853, "Kaocto")],
    "fatalitee" : [(854, "Fatalitee")],
    "mortipot" : [(855, "Mortipot")],
    "brimova" : [(856, "Brimova")],
    "brimano" : [(857, "Brimano")],
    "silembrim" : [(858, "Silembrim")],
    "bähmon" : [(859, "Bähmon")],
    "baehmon" : [(859, "Bähmon")],
    "bahmon" : [(859, "Bähmon")],
    "pelzebub" : [(860, "Pelzebub")],
    "olangaar" : [(861, "Olangaar")],
    "barrikadax" : [(862, "Barrikadax")],
    "mauzinger" : [(863, "Mauzinger")],
    "gorgasonn" : [(864, "Gorgasonn")],
    "lauchzelot" : [(865, "Lauchzelot")],
    "pantifrost" : [(866, "Pantifrost")],
    "oghnatoll" : [(867, "Oghnatoll")],
    "hokumil" : [(868, "Hokumil")],
    "pokusan" : [(869, "Pokusan")],
    "legios" : [(870, "Legios")],
    "britzigel" : [(871, "Britzigel")],
    "snomnom" : [(872, "Snomnom")],
    "mottineva" : [(873, "Mottineva")],
    "humanolith" : [(874, "Humanolith")],
    "kubuin" : [(875, "Kubuin")],
    "servol" : [(876, "Servol")],
    "morpeko" : [(877, "Morpeko")],
    "kupfanti" : [(878, "Kupfanti")],
    "patinaraja" : [(879, "Patinaraja")],
    "lectragon" : [(880, "Lectragon")],
    "lecryodon" : [(881, "Lecryodon")],
    "pescragon" : [(882, "Pescragon")],
    "pescryodon" : [(883, "Pescryodon")],
    "duraludon" : [(884, "Duraludon")],
    "grolldra" : [(885, "Grolldra")],
    "phandra" : [(886, "Phandra")],
    "katapuldra" : [(887, "Katapuldra")],
    "zacian" : [(888, "Zacian")],
    "zamazenta" : [(889, "Zamazenta")],
    "endynalos" : [(890, "Endynalos")],
    "dakuma" : [(891, "Dakuma")],
    "wulaosu" : [(892, "Wulaosu")],
    "zarude" : [(893, "Zarude")],
    "regieleki" : [(894, "Regieleki")],
    "regidrago" : [(895, "Regidrago")],
    "polaross" : [(896, "Polaross")],
    "phantoross" : [(897, "Phantoross")],
    "coronospa" : [(898, "Coronospa")],
    "damythir" : [(899, "Damythir")],
    "axantor" : [(900, "Axantor")],
    "ursaluna" : [(901, "Ursaluna")],
    "salmagnis" : [(902, "Salmagnis")],
    "snieboss" : [(903, "Snieboss")],
    "myriador" : [(904, "Myriador")],
    "cupidos" : [(905, "Cupidos")],
}


gen_name_all = {**gen_name_eng, **gen_name_ger}

# dict id -> name

gen_id_eng = {
    810 : "Grookey",
    811 : "Thwackey",
    812 : "Rillaboom",
    813 : "Scorbunny",
    814 : "Raboot",
    815 : "Cinderace",
    816 : "Sobble",
    817 : "Drizzile",
    818 : "Inteleon",
    819 : "Skwovet",
    820 : "Greedent",
    821 : "Rookidee",
    822 : "Corvisquire",
    823 : "Corviknight",
    824 : "Blipbug",
    825 : "Dottler",
    826 : "Orbeetle",
    827 : "Nickit",
    828 : "Thievul",
    829 : "Gossifleur",
    830 : "Eldegoss",
    831 : "Wooloo",
    832 : "Dubwool",
    833 : "Chewtle",
    834 : "Drednaw",
    835 : "Yamper",
    836 : "Boltund",
    837 : "Rolycoly",
    838 : "Carkol",
    839 : "Coalossal",
    840 : "Applin",
    841 : "Flapple",
    842 : "Appletun",
    843 : "Silicobra",
    844 : "Sandaconda",
    845 : "Cramorant",
    846 : "Arrokuda",
    847 : "Barraskewda",
    848 : "Toxel",
    849 : "Toxtricity",
    850 : "Sizzlipede",
    851 : "Centiskorch",
    852 : "Clobbopus",
    853 : "Grapploct",
    854 : "Sinistea",
    855 : "Polteageist",
    856 : "Hatenna",
    857 : "Hattrem",
    858 : "Hatterene",
    859 : "Impidimp",
    860 : "Morgrem",
    861 : "Grimmsnarl",
    862 : "Obstagoon",
    863 : "Perrserker",
    864 : "Cursola",
    865 : "Sirfetch’d",
    866 : "Mr. Rime",
    867 : "Runerigus",
    868 : "Milcery",
    869 : "Alcremie",
    870 : "Falinks",
    871 : "Pincurchin",
    872 : "Snom",
    873 : "Frosmoth",
    874 : "Stonjourner",
    875 : "Eiscue",
    876 : "Indeedee",
    877 : "Morpeko",
    878 : "Cufant",
    879 : "Copperajah",
    880 : "Dracozolt",
    881 : "Arctozolt",
    882 : "Dracovish",
    883 : "Arctovish",
    884 : "Duraludon",
    885 : "Dreepy",
    886 : "Drakloak",
    887 : "Dragapult",
    888 : "Zacian",
    889 : "Zamazenta",
    890 : "Eternatus",
    891 : "Kubfu",
    892 : "Urshifu",
    893 : "Zarude",
    894 : "Regieleki",
    895 : "Regidrago",
    896 : "Glastrier",
    897 : "Spectrier",
    898 : "Calyrex",
    899 : "Wyrdeer",
    900 : "Kleavor",
    901 : "Ursaluna",
    902 : "Basculegion",
    903 : "Sneasler",
    904 : "Overqwil",
    905 : "Enamorus",
}

gen_id_all = gen_id_eng

gen_id_ger = {
    810 : "Chimpep",
    811 : "Chimstix",
    812 : "Gortrom",
    813 : "Hopplo",
    814 : "Kickerlo",
    815 : "Liberlo",
    816 : "Memmeon",
    817 : "Phlegleon",
    818 : "Intelleon",
    819 : "Raffel",
    820 : "Schlaraffel",
    821 : "Meikro",
    822 : "Kranoviz",
    823 : "Krarmor",
    824 : "Sensect",
    825 : "Keradar",
    826 : "Maritellit",
    827 : "Kleptifux",
    828 : "Gaunux",
    829 : "Cottini",
    830 : "Cottomi",
    831 : "Wolly",
    832 : "Zwollock",
    833 : "Kamehaps",
    834 : "Kamalm",
    835 : "Voldi",
    836 : "Bellektro",
    837 : "Klonkett",
    838 : "Wagong",
    839 : "Montecarbo",
    840 : "Knapfel",
    841 : "Drapfel",
    842 : "Schlapfel",
    843 : "Salanga",
    844 : "Sanaconda",
    845 : "Urgl",
    846 : "Pikuda",
    847 : "Barrakiefa",
    848 : "Toxel",
    849 : "Riffex",
    850 : "Thermopod",
    851 : "Infernopod",
    852 : "Klopptopus",
    853 : "Kaocto",
    854 : "Fatalitee",
    855 : "Mortipot",
    856 : "Brimova",
    857 : "Brimano",
    858 : "Silembrim",
    859 : "Bähmon",
    860 : "Pelzebub",
    861 : "Olangaar",
    862 : "Barrikadax",
    863 : "Mauzinger",
    864 : "Gorgasonn",
    865 : "Lauchzelot",
    866 : "Pantifrost",
    867 : "Oghnatoll",
    868 : "Hokumil",
    869 : "Pokusan",
    870 : "Legios",
    871 : "Britzigel",
    872 : "Snomnom",
    873 : "Mottineva",
    874 : "Humanolith",
    875 : "Kubuin",
    876 : "Servol",
    877 : "Morpeko",
    878 : "Kupfanti",
    879 : "Patinaraja",
    880 : "Lectragon",
    881 : "Lecryodon",
    882 : "Pescragon",
    883 : "Pescryodon",
    884 : "Duraludon",
    885 : "Grolldra",
    886 : "Phandra",
    887 : "Katapuldra",
    888 : "Zacian",
    889 : "Zamazenta",
    890 : "Endynalos",
    891 : "Dakuma",
    892 : "Wulaosu",
    893 : "Zarude",
    894 : "Regieleki",
    895 : "Regidrago",
    896 : "Polaross",
    897 : "Phantoross",
    898 : "Coronospa",
    899 : "Damythir",
    900 : "Axantor",
    901 : "Ursaluna",
    902 : "Salmagnis",
    903 : "Snieboss",
    904 : "Myriador",
    905 : "Cupidos",
}