gen_name_eng = {
    "sprigatito"    : [(906, "Sprigatito")],
    "floragato"     : [(907, "Floragato")],
    "meowscarada"   : [(908, "Meowscarada")],
    "fuecoco"       : [(909, "Fuecoco")],
    "crocalor"      : [(910, "Crocalor")],
    "skeledirge"    : [(911, "Skeledirge")],
    "quaxly"        : [(912, "Quaxly")],
    "quaxwell"      : [(913, "Quaxwell")],
    "quaquaval"     : [(914, "Quaquaval")],
    "lechonk"       : [(915, "Lechonk")],
    "oinkologne"    : [(916, "Oinkologne")],
    "tarountula"    : [(917, "Tarountula")],
    "spidops"       : [(918, "Spidops")],
    "nymble"        : [(919, "Nymble")],
    "lokix"         : [(920, "Lokix")],
    "pawmi"         : [(921, "Pawmi")],
    "pawmo"         : [(922, "Pawmo")],
    "pawmot"        : [(923, "Pawmot")],
    "tandemaus"     : [(924, "Tandemaus")],
    "maushold"      : [(925, "Maushold")],
    "fidough"       : [(926, "Fidough")],
    "dachsbun"      : [(927, "Dachsbun")],
    "smoliv"        : [(928, "Smoliv")],
    "dolliv"        : [(929, "Dolliv")],
    "arboliva"      : [(930, "Arboliva")],
    "squawkabilly"  : [(931, "Squawkabilly")],
    "nacli"         : [(932, "Nacli")],
    "naclstack"     : [(933, "Naclstack")],
    "garganacl"     : [(934, "Garganacl")],
    "charcadet"     : [(935, "Charcadet")],
    "armarouge"     : [(936, "Armarouge")],
    "ceruledge"     : [(937, "Ceruledge")],
    "tadbulb"       : [(938, "Tadbulb")],
    "bellibolt"     : [(939, "Bellibolt")],
    "wattrel"       : [(940, "Wattrel")],
    "kilowattrel"   : [(941, "Kilowattrel")],
    "maschiff"      : [(942, "Maschiff")],
    "mabosstiff"    : [(943, "Mabosstiff")],
    "shroodle"      : [(944, "Shroodle")],
    "grafaiai"      : [(945, "Grafaiai")],
    "bramblin"      : [(946, "Bramblin")],
    "brambleghast"  : [(947, "Brambleghast")],
    "toedscool"     : [(948, "Toedscool")],
    "toedscruel"    : [(949, "Toedscruel")],
    "klawf"         : [(950, "Klawf")],
    "capsakid"      : [(951, "Capsakid")],
    "scovillain"    : [(952, "Scovillain")],
    "rellor"        : [(953, "Rellor")],
    "rabsca"        : [(954, "Rabsca")],
    "flittle"       : [(955, "Flittle")],
    "espathra"      : [(956, "Espathra")],
    "tinkatink"     : [(957, "Tinkatink")],
    "tinkatuff"     : [(958, "Tinkatuff")],
    "tinkaton"      : [(959, "Tinkaton")],
    "wiglett"       : [(960, "Wiglett")],
    "wugtrio"       : [(961, "Wugtrio")],
    "bombirdier"    : [(962, "Bombirdier")],
    "finizen"       : [(963, "Finizen")],
    "palafin"       : [(964, "Palafin")],
    "varoom"        : [(965, "Varoom")],
    "revavroom"     : [(966, "Revavroom")],
    "cyclizar"      : [(967, "Cyclizar")],
    "orthworm"      : [(968, "Orthworm")],
    "glimmet"       : [(969, "Glimmet")],
    "glimmora"      : [(970, "Glimmora")],
    "greavard"      : [(971, "Greavard")],
    "houndstone"    : [(972, "Houndstone")],
    "flamigo"       : [(973, "Flamigo")],
    "cetoddle"      : [(974, "Cetoddle")],
    "cetitan"       : [(975, "Cetitan")],
    "veluza"        : [(976, "Veluza")],
    "dondozo"       : [(977, "Dondozo")],
    "tatsugiri"     : [(978, "Tatsugiri")],
    "annihilape"    : [(979, "Annihilape")],
    "clodsire"      : [(980, "Clodsire")],
    "farigiraf"     : [(981, "Farigiraf")],
    "dudunsparce"   : [(982, "Dudunsparce")],
    "kingambit"     : [(983, "Kingambit")],
    "great tusk "   : [(984, "Great Tusk")],
    "greattusk "   : [(984, "Great Tusk")],
    "scream tail"   : [(985, "Scream Tail")],
    "screamtail"   : [(985, "Scream Tail")],
    "brute bonnet"  : [(986, "Brute Bonnet")],
    "brutebonnet"  : [(986, "Brute Bonnet")],
    "flutter mane"  : [(987, "Flutter Mane")],
    "fluttermane"  : [(987, "Flutter Mane")],
    "slither wing"  : [(988, "Slither Wing")],
    "slitherwing"  : [(988, "Slither Wing")],
    "sandy shocks"  : [(989, "Sandy Shocks")],
    "sandyshocks"  : [(989, "Sandy Shocks")],
    "iron treads"   : [(990, "Iron Treads")],
    "irontreads"   : [(990, "Iron Treads")],
    "iron bundle"   : [(991, "Iron Bundle")],
    "ironbundle"   : [(991, "Iron Bundle")],
    "iron hands"    : [(992, "Iron Hands")],
    "ironhands"    : [(992, "Iron Hands")],
    "iron jugulis"  : [(993, "Iron Jugulis")],
    "ironjugulis"  : [(993, "Iron Jugulis")],
    "iron moth"     : [(994, "Iron Moth")],
    "ironmoth"     : [(994, "Iron Moth")],
    "iron thorns"   : [(995, "Iron Thorns")],
    "ironthorns"   : [(995, "Iron Thorns")],
    "frigibax"      : [(996, "Frigibax")],
    "arctibax"      : [(997, "Arctibax")],
    "baxcalibur"    : [(998, "Baxcalibur")],
    "gimmighoul"    : [(999, "Gimmighoul")],
    "gholdengo"     : [(1000, "Gholdengo")],
    "wo-chien"      : [(1001, "Wo-Chien")],
    "wo chien"      : [(1001, "Wo-Chien")],
    "wochien"      : [(1001, "Wo-Chien")],    
    "chien-pao"     : [(1002, "Chien-Pao")],
    "chien pao"     : [(1002, "Chien-Pao")],
    "chienpao"     : [(1002, "Chien-Pao")],
    "ting-lu"       : [(1003, "Ting-Lu")],
    "ting lu"       : [(1003, "Ting-Lu")],
    "tinglu"       : [(1003, "Ting-Lu")],
    "chi-yu "       : [(1004, "Chi-Yu")],
    "chi yu "       : [(1004, "Chi-Yu")],
    "chiyu "       : [(1004, "Chi-Yu")],
    "roaring moon"  : [(1005, "Roaring Moon")],
    "roaringmoon"  : [(1005, "Roaring Moon")],
    "iron valiant"  : [(1006, "Iron Valiant")],
    "ironvaliant"  : [(1006, "Iron Valiant")],
    "koraidon"      : [(1007, "Koraidon")],
    "miraidon"      : [(1008, "Miraidon")],
    "walking wake"  : [(1009, "Walking Wake")],
    "walkingwake"  : [(1009, "Walking Wake")],
    "iron leaves"   : [(1010, "Iron Leaves")],
    "ironleaves"   : [(1010, "Iron Leaves")],
    "okidogi"       : [(1011, "Okidogi")],
    "munkidori"     : [(1012, "Munkidori")],
    "fezandipiti"   : [(1013, "Fezandipiti")],
    "ogerpon"       : [(1014, "Ogerpon")],
    "terapagos"     : [(1015, "Terapagos")],
}

gen_name_ger = {
    "felori"        : [(906, "Felori")],
    "feliospa"      : [(907, "Feliospa")],
    "maskagato"     : [(908, "Maskagato")],
    "krokel"        : [(909, "Krokel")],
    "lokroko"       : [(910, "Lokroko")],
    "skelokrok"     : [(911, "Skelokrok")],
    "kwaks"         : [(912, "Kwaks")],
    "fuentente"     : [(913, "Fuentente")],
    "bailonda"      : [(914, "Bailonda")],
    "ferkuli"       : [(915, "Ferkuli")],
    "fragrunz"      : [(916, "Fragrunz")],
    "tarundel"      : [(917, "Tarundel")],
    "spinsidias"    : [(918, "Spinsidias")],
    "micrick"       : [(919, "Micrick")],
    "lextremo"      : [(920, "Lextremo")],
    "pamo"          : [(921, "Pamo")],
    "pamamo"        : [(922, "Pamamo")],
    "pamomamo"      : [(923, "Pamomamo")],
    "zwieps"        : [(924, "Zwieps")],
    "famieps"       : [(925, "Famieps")],
    "hefel"         : [(926, "Hefel")],
    "backel"        : [(927, "Backel")],
    "olini"         : [(928, "Olini")],
    "olivinio"      : [(929, "Olivinio")],
    "olithena"      : [(930, "Olithena")],
    "krawalloro"    : [(931, "Krawalloro")],
    "geosali"       : [(932, "Geosali")],
    "sedisal"       : [(933, "Sedisal")],
    "saltigant"     : [(934, "Saltigant")],
    "knarbon"       : [(935, "Knarbon")],
    "crimanzo"      : [(936, "Crimanzo")],
    "azugladis"     : [(937, "Azugladis")],
    "blipp"         : [(938, "Blipp")],
    "wampitz"       : [(939, "Wampitz")],
    "voltrel"       : [(940, "Voltrel")],
    "voltrean"      : [(941, "Voltrean")],
    "mobtiff"       : [(942, "Mobtiff")],
    "mastifioso"    : [(943, "Mastifioso")],
    "sproxi"        : [(944, "Sproxi")],
    "affiti"        : [(945, "Affiti")],
    "weherba"       : [(946, "Weherba")],
    "horrerba"      : [(947, "Horrerba")],
    "tentagra"      : [(948, "Tentagra")],
    "tenterra"      : [(949, "Tenterra")],
    "klibbe"        : [(950, "Klibbe")],
    "chilingel"     : [(951, "Chilingel")],
    "halupenjo"     : [(952, "Halupenjo")],
    "relluk"        : [(953, "Relluk")],
    "skarabaks"     : [(954, "Skarabaks")],
    "flattutu"      : [(955, "Flattutu")],
    "psiopatra"     : [(956, "Psiopatra")],
    "forgita"       : [(957, "Forgita")],
    "tafforgita"    : [(958, "Tafforgita")],
    "granforgita"   : [(959, "Granforgita")],
    "schligda"      : [(960, "Schligda")],
    "schligdri"     : [(961, "Schligdri")],
    "adebom"        : [(962, "Adebom")],
    "normifin"      : [(963, "Normifin")],
    "delfinator"    : [(964, "Delfinator")],
    "knattox"       : [(965, "Knattox")],
    "knattatox"     : [(966, "Knattatox")],
    "mopex"         : [(967, "Mopex")],
    "schlurm"       : [(968, "Schlurm")],
    "lumispross"    : [(969, "Lumispross")],
    "lumiflora"     : [(970, "Lumiflora")],
    "gruff"         : [(971, "Gruff")],
    "friedwuff"     : [(972, "Friedwuff")],
    "flaminkno"     : [(973, "Flaminkno")],
    "flaniwal"      : [(974, "Flaniwal")],
    "kolowal"       : [(975, "Kolowal")],
    "agiluza"       : [(976, "Agiluza")],
    "heerashai"     : [(977, "Heerashai")],
    "nigiragi"      : [(978, "Nigiragi")],
    "epitaff"       : [(979, "Epitaff")],
    "suelord"       : [(980, "Suelord")],
    "farigiraf"     : [(981, "Farigiraf")],
    "dummimisel"    : [(982, "Dummimisel")],
    "gladimperio"   : [(983, "Gladimperio")],
    "riesenzahn"    : [(984, "Riesenzahn")],
    "brüllschweif"  : [(985, "Brüllschweif")],
    "brullschweif"  : [(985, "Brüllschweif")],
    "bruellschweif"  : [(985, "Brüllschweif")],
    "wutpilz"       : [(986, "Wutpilz")],
    "flatterhaar"   : [(987, "Flatterhaar")],
    "kriechflügel"  : [(988, "Kriechflügel")],
    "kriechflugel"  : [(988, "Kriechflügel")],
    "kriechfluegel"  : [(988, "Kriechflügel")],
    "sandfell"      : [(989, "Sandfell")],
    "eisenrad"      : [(990, "Eisenrad")],
    "eisenbündel"   : [(991, "Eisenbündel")],
    "eisenbundel"   : [(991, "Eisenbündel")],
    "eisenbuendel"   : [(991, "Eisenbündel")],
    "eisenhand"     : [(992, "Eisenhand")],
    "eisenhals"     : [(993, "Eisenhals")],
    "eisenfalter"   : [(994, "Eisenfalter")],
    "eisendorn"     : [(995, "Eisendorn")],
    "frospino"      : [(996, "Frospino")],
    "cryospino"     : [(997, "Cryospino")],
    "espinodon"     : [(998, "Espinodon")],
    "gierspenst"    : [(999, "Gierspenst")],
    "monetigo"      : [(1000, "Monetigo")],
    "chongjian"     : [(1001, "Chongjian")],
    "baojian"       : [(1002, "Baojian")],
    "dinglu"        : [(1003, "Dinglu")],
    "yuyu"          : [(1004, "Yuyu")],
    "donnersichel"  : [(1005, "Donnersichel")],
    "eisenkrieger"  : [(1006, "Eisenkrieger")],
    "koraidon"      : [(1007, "Koraidon")],
    "miraidon"      : [(1008, "Miraidon")],
    "windewoge"     : [(1009, "Windewoge")],
    "eisenblatt"    : [(1010, "Eisenblatt")],
    "boninu"        : [(1011, "Boninu")],
    "benesaru"      : [(1012, "Benesaru")],
    "beatori"       : [(1013, "Beatori")],
    "ogerpon"       : [(1014, "Ogerpon")],
    "terapagos"     : [(1015, "Terapagos")],
}


gen_name_all = {**gen_name_eng, **gen_name_ger}

# dict id -> name

gen_id_eng = {
    906 : "Sprigatito",
    907 : "Floragato",
    908 : "Meowscarada",
    909 : "Fuecoco",
    910 : "Crocalor",
    911 : "Skeledirge",
    912 : "Quaxly",
    913 : "Quaxwell",
    914 : "Quaquaval",
    915 : "Lechonk",
    916 : "Oinkologne",
    917 : "Tarountula",
    918 : "Spidops",
    919 : "Nymble",
    920 : "Lokix",
    921 : "Pawmi",
    922 : "Pawmo",
    923 : "Pawmot",
    924 : "Tandemaus",
    925 : "Maushold",
    926 : "Fidough",
    927 : "Dachsbun",
    928 : "Smoliv",
    929 : "Dolliv",
    930 : "Arboliva",
    931 : "Squawkabilly",
    932 : "Nacli",
    933 : "Naclstack",
    934 : "Garganacl",
    935 : "Charcadet",
    936 : "Armarouge",
    937 : "Ceruledge",
    938 : "Tadbulb",
    939 : "Bellibolt",
    940 : "Wattrel",
    941 : "Kilowattrel",
    942 : "Maschiff",
    943 : "Mabosstiff",
    944 : "Shroodle",
    945 : "Grafaiai",
    946 : "Bramblin",
    947 : "Brambleghast",
    948 : "Toedscool",
    949 : "Toedscruel",
    950 : "Klawf",
    951 : "Capsakid",
    952 : "Scovillain",
    953 : "Rellor",
    954 : "Rabsca",
    955 : "Flittle",
    956 : "Espathra",
    957 : "Tinkatink",
    958 : "Tinkatuff",
    959 : "Tinkaton",
    960 : "Wiglett",
    961 : "Wugtrio",
    962 : "Bombirdier",
    963 : "Finizen",
    964 : "Palafin",
    965 : "Varoom",
    966 : "Revavroom",
    967 : "Cyclizar",
    968 : "Orthworm",
    969 : "Glimmet",
    970 : "Glimmora",
    971 : "Greavard",
    972 : "Houndstone",
    973 : "Flamigo",
    974 : "Cetoddle",
    975 : "Cetitan",
    976 : "Veluza",
    977 : "Dondozo",
    978 : "Tatsugiri",
    979 : "Annihilape",
    980 : "Clodsire",
    981 : "Farigiraf",
    982 : "Dudunsparce",
    983 : "Kingambit",
    984 : "Great Tusk",
    985 : "Scream Tail",
    986 : "Brute Bonnet",
    987 : "Flutter Mane",
    988 : "Slither Wing",
    989 : "Sandy Shocks",
    990 : "Iron Treads",
    991 : "Iron Bundle",
    992 : "Iron Hands",
    993 : "Iron Jugulis",
    994 : "Iron Moth",
    995 : "Iron Thorns",
    996 : "Frigibax",
    997 : "Arctibax",
    998 : "Baxcalibur",
    999 : "Gimmighoul",
    1000 : "Gholdengo",
    1001 : "Wo-Chien",
    1002 : "Chien-Pao",
    1003 : "Ting-Lu",
    1004 : "Chi-Yu",
    1005 : "Roaring Moon",
    1006 : "Iron Valiant",
    1007 : "Koraidon",
    1008 : "Miraidon",
    1009 : "Walking Wake",
    1010 : "Iron Leaves",
    1011 : "Okidogi",
    1012 : "Munkidori",
    1013 : "Fezandipiti",
    1014 : "Ogerpon",
    1015 : "Terapagos",
}

gen_id_all = gen_id_eng

gen_id_ger = {
    906 : "Felori",
    907 : "Feliospa",
    908 : "Maskagato",
    909 : "Krokel",
    910 : "Lokroko",
    911 : "Skelokrok",
    912 : "Kwaks",
    913 : "Fuentente",
    914 : "Bailonda",
    915 : "Ferkuli",
    916 : "Fragrunz",
    917 : "Tarundel",
    918 : "Spinsidias",
    919 : "Micrick",
    920 : "Lextremo",
    921 : "Pamo",
    922 : "Pamamo",
    923 : "Pamomamo",
    924 : "Zwieps",
    925 : "Famieps",
    926 : "Hefel",
    927 : "Backel",
    928 : "Olini",
    929 : "Olivinio",
    930 : "Olithena",
    931 : "Krawalloro",
    932 : "Geosali",
    933 : "Sedisal",
    934 : "Saltigant",
    935 : "Knarbon",
    936 : "Crimanzo",
    937 : "Azugladis",
    938 : "Blipp",
    939 : "Wampitz",
    940 : "Voltrel",
    941 : "Voltrean",
    942 : "Mobtiff",
    943 : "Mastifioso",
    944 : "Sproxi",
    945 : "Affiti",
    946 : "Weherba",
    947 : "Horrerba",
    948 : "Tentagra",
    949 : "Tenterra",
    950 : "Klibbe",
    951 : "Chilingel",
    952 : "Halupenjo",
    953 : "Relluk",
    954 : "Skarabaks",
    955 : "Flattutu",
    956 : "Psiopatra",
    957 : "Forgita",
    958 : "Tafforgita",
    959 : "Granforgita",
    960 : "Schligda",
    961 : "Schligdri",
    962 : "Adebom",
    963 : "Normifin",
    964 : "Delfinator",
    965 : "Knattox",
    966 : "Knattatox",
    967 : "Mopex",
    968 : "Schlurm",
    969 : "Lumispross",
    970 : "Lumiflora",
    971 : "Gruff",
    972 : "Friedwuff",
    973 : "Flaminkno",
    974 : "Flaniwal",
    975 : "Kolowal",
    976 : "Agiluza",
    977 : "Heerashai",
    978 : "Nigiragi",
    979 : "Epitaff",
    980 : "Suelord",
    981 : "Farigiraf",
    982 : "Dummimisel",
    983 : "Gladimperio",
    984 : "Riesenzahn",
    985 : "Brüllschweif",
    986 : "Wutpilz",
    987 : "Flatterhaar",
    988 : "Kriechflügel",
    989 : "Sandfell",
    990 : "Eisenrad",
    991 : "Eisenbündel",
    992 : "Eisenhand",
    993 : "Eisenhals",
    994 : "Eisenfalter",
    995 : "Eisendorn",
    996 : "Frospino",
    997 : "Cryospino",
    998 : "Espinodon",
    999 : "Gierspenst",
    1000 : "Monetigo",
    1001 : "Chongjian",
    1002 : "Baojian",
    1003 : "Dinglu",
    1004 : "Yuyu",
    1005 : "Donnersichel",
    1006 : "Eisenkrieger",
    1007 : "Koraidon",
    1008 : "Miraidon",
    1009 : "Windewoge",
    1010 : "Eisenblatt",
    1011 : "Okidogi",
    1012 : "Munkidori",
    1013 : "Fezandipiti",
    1014 : "Ogerpon",
    1015 : "Terapagos",
}